### ISSUE TITLE
Can't harvest the Croparia's crop

### ISSUE THREAD

**Issue by ffffffffawd** [koelle25/Right-Click-Harvest#2]

**Comment by koelle25** [comment]
Hi!

Sorry for answering so late, GitHub apparently thought I wouldn't want to be notified about any activity in this repository... Oh well.

Currently this mod does only work on a static list of crops (wheat, carrots, potato, beetroot, nether wart). 

I think I could implement it in a way that all blocks with the `minecraft:crops` tag would be considered.
The problem with [Croparia](https://github.com/Dalarion/Croparia) is that it doesn't use these tags. Instead, as far as I have read, it wants the player to craft and use the `knife` item to harvest its crops.

For this reason I will close this issue for now. Maybe in the future Croparia adds the tag to its crops (you could of course open an issue regarding this [over there](https://github.com/Dalarion/Croparia/issues)), then I will look into it again.

**Comment by TheSnowyChickens** [comment]
Hello,

what about ValleyCraft crops ?

**Comment by TheSnowyChickens** [comment]
Soo I still need to create a new request "issue" for that, if it is already implemented ? :D

**Comment by koelle25** [comment]
No, of course not. Right click harvesting is already working for ValleyCraft crops, I actually tested it myself.

This mod here is only needed for Minecraft Vanilla crops.

**Comment by TheSnowyChickens** [comment]
Maybe a future update, after my comment here, fixed/implemented it.

I am updating my modpack to 1.18.2 atm (took long because end remastered), great to see the right click feature then.^^

Ty for your work anyways. 👍
